/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002204",
        "tertiary-container": "#782e97",
        "tertiary-fixed-dim": "#ecb2ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#dde9f9",
        "outline-variant": "#c0c9bf",
        "on-primary-container": "#90d2a5",
        "on-tertiary-container": "#eaaeff",
        "inverse-surface": "#26323d",
        "secondary-fixed-dim": "#78dc77",
        "primary-fixed-dim": "#93d5a7",
        "surface-container-low": "#ecf4ff",
        "secondary-fixed": "#94f990",
        "secondary": "#006e1c",
        "surface": "#f7f9ff",
        "primary-container": "#1a5c38",
        "surface-variant": "#d7e4f3",
        "on-error": "#ffffff",
        "on-primary-fixed": "#00210f",
        "on-tertiary-fixed": "#320047",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#0b522f",
        "primary-fixed": "#aef2c2",
        "surface-container": "#e3effe",
        "on-secondary-container": "#00731e",
        "surface-tint": "#2a6a45",
        "surface-dim": "#cfdbea",
        "error": "#ba1a1a",
        "surface-container-highest": "#d7e4f3",
        "outline": "#707971",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#e7f2ff",
        "on-surface": "#111d27",
        "on-surface-variant": "#404941",
        "on-background": "#111d27",
        "inverse-primary": "#93d5a7",
        "on-secondary-fixed-variant": "#005313",
        "background": "#f7f9ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#6c228c",
        "secondary-container": "#91f78e",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#f8d8ff",
        "primary": "#004324",
        "surface-bright": "#f7f9ff",
        "tertiary": "#5e0e7e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "40px",
        "sm": "16px",
        "base": "4px",
        "gutter": "20px",
        "margin-mobile": "16px",
        "xs": "8px",
        "xl": "64px",
        "margin-desktop": "32px",
        "md": "24px"
      },
      fontFamily: {
        "mono-data": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
